### PR TITLE
"larsoft

### PR DESCRIPTION
**Pull request by lgarren**

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build with pull requests https://github.com/LArSoft/larwirecell/pull/1 https://github.com/LArSoft/larutils/pull/1 https://github.com/LArSoft/larsoftobj/pull/1 https://github.com/LArSoft/larsoft/pull/2 https://github.com/LArSoft/larsim/pull/2 https://github.com/LArSoft/larreco/pull/2 https://github.com/LArSoft/larpandora/pull/1 https://github.com/LArSoft/larg4/pull/1 https://github.com/LArSoft/larexamples/pull/1 https://github.com/LArSoft/larevt/pull/1 https://github.com/LArSoft/lareventdisplay/pull/1 https://github.com/LArSoft/lardataobj/pull/1 https://github.com/LArSoft/lardataalg/pull/1 https://github.com/LArSoft/lardata/pull/2 https://github.com/LArSoft/larcoreobj/pull/1 https://github.com/LArSoft/larcorealg/pull/1 https://github.com/LArSoft/larcore/pull/1 https://github.com/LArSoft/larana/pull/1

**Comment by gartung** [comment]
The process_pr.py script failed to parse that and trigger the downstream jenkins jobs. Investigating now.

**Comment by lgarren** [comment]
@gartung Would a different format be better?

**Comment by gartung** [comment]
It is supposed to handle any form mention on
https://cdcvs.fnal.gov/redmine/projects/larsoft/wiki/Pull_request_comments_that_trigger_CI_actions

**Comment by gartung** [comment]
trigger build using branchnames release/v08_41_01 in repos larwirecell,larutils,larsoftobj,larsim,larreco,larpandora,larg4,larexamples,larevt,lareventdisplay,lardataobj,lardataalg,lardata,larcoreobj,larcorealg,larcore,larana

**Comment by gartung** [comment]
The second form triggered the chain of jenkins jobs that runs lar_ci see
https://buildmaster.fnal.gov/buildmaster/job/lar_ci/7655/

**Comment by gartung** [comment]
Although it seems to have picked up larreco#1 and larsim#1 which was not intended.

**Comment by gartung** [comment]
trigger build with pull requests larana#1,larcor#1,larcorealg#1,larcoreobj#1,lardata#2,lardataalg#1,lardataobj#1,lareventdisplay#1,larevt#1,larexamples#1,larg4#1,larpandora#1,larreco#2,larsim#2,larsoftobj#1,larwirecell#1

**Comment by gartung** [comment]
Removing previous trigger build messages so it will pick up the latest request.

**Comment by gartung** [comment]
Making changes to this close pull request for testing.

**Comment by gartung** [comment]
trigger build with https://github.com/LArSoft/larwirecell/pull/1, https://github.com/LArSoft/larutils/pull/1, https://github.com/LArSoft/larutils/pull/1, https://github.com/LArSoft/larsoftobj/pull/1, https://github.com/LArSoft/larsim/pull/2, https://github.com/LArSoft/larreco/pull/2, https://github.com/LArSoft/larpandora/pull/1, https://github.com/LArSoft/larg4/pull/1, https://github.com/LArSoft/larexamples/pull/1, https://github.com/LArSoft/larevt/pull/1, https://github.com/LArSoft/lareventdisplay/pull/1, https://github.com/LArSoft/lardataobj/pull/1, https://github.com/LArSoft/lardataalg/pull/1, https://github.com/LArSoft/lardata/pull/2, https://github.com/LArSoft/larcoreobj/pull/1, https://github.com/LArSoft/larcorealg/pull/1, https://github.com/LArSoft/larcore/pull/1, https://github.com/LArSoft/larana/pull/1

**Comment by gartung** [comment]
trigger build using branchname release/v08_41_01 in repos larana, larcore, larcorealg, larcoreobj, lardata, lardataalg, lardataobj, larevt, lareventdisplay, larexamples, larg4, larpandora, larreco, larsim, larsoft, larsoftobj, larwirecell

**Pull request merged**
